### ISSUE TITLE
Error records not seen in events section

### ISSUE THREAD

**Issue by harunyasar** [hibou-io/odoo-newrelic#2]
Could you please help about this issue? I'm following your instruction steps and the agents are working correctly but there have no any knowledge about error rate. For example in main.py example so the raised ValueError is not seen in errors section.

**Comment by jaredkipe** [comment]
Most likely this is because the 'dev_mode' isn't active.  Try checking out the current '9.0' branch and making sure the config file has 'debug_mode = True' in it. 

Alternatively, you can do the same thing on the '10.0' branch which I JUST tested and upgraded for Odoo v10.  (including testing those routes and making sure that the expected errors came through to NewRelic)

You'll know you're on the right track when the results for those routes are 'unstyled' 404's or Internal Errors.
